openapi: 3.0.3
info:
  title: STD24005
  description: This is a specification of STD24005
  version: 1.0.0
servers:
  - url: localhost:8000
paths:
  /ping:
    get:
      responses:
        '200':
          description: Endpoint returning pong
          content:
          text/plain:
            type: string
            example: pong

  /cars:
    get:
      responses:
        '200':
          description: Endpoint returning the actual car list
            content:
            application/json:
              type: array
              example: [{}]

        
  
